apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yummyapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yummyapi
    spec:
      containers:
        - name: yummy
          image: philophilo/yummy
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yummyapi
  labels:
    app: yummyapi
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31818
  selector:
    app: yummyapi

