default: &defaults
  docker:
    - image: 'philophilo/awskube'
      environment:
        TestingConfig: 'TestingConfig'
        DATABASE_URL: 'postgresql://postgres@localhost/postgres?sslmode=disable'
    - image: 'circleci/postgres:9.6.5-alpine-ram'
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: test_db
        POSTGRES_PASSWORD: ''
  working_directory: ~/project

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: mkdir test-reports
      - restore_cache:
          key: 'deps1-{{ .Branch }}-{{ checksum "yummy_api/requirements.txt" }}'
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd yummy_api/
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            cd yummy_api/
            nosetests --with-coverage --cover-package=app
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

  deploy:
    docker:
      - image: 'philophilo/awskube'
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose up -d
            docker-compose push
      - run:
          name: Deploy
          command: |
            kops export kubecfg ${CLUSTER_NAME} --state=s3://${BUCKET_NAME}
            kubectl apply -f ~/project/deployment.yml
    working_directory: ~/project

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
