language: python
python:
  - 3.6.3
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
before_script:
  - psql -c 'CREATE DATABASE yummy;' -U postgres
  - psql -c 'CREATE DATABASE test_yummy;' -U postgres
  - sh travis_db.sh

env:
  DATABASE_URL = 'postgresql://localhost/test_yummy'
script:
  - nosetests --with-coverage --cover-package=app
after_success:
  - coveralls
  - codeclimate
